-- 1. Create separate, normalized tables
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT,
    demo_url TEXT,
    github_url TEXT,
    image_url TEXT,
    tech_stack TEXT[],
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    demo_url TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    title TEXT NOT NULL,
    issuer TEXT,
    category TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    period TEXT,
    icon_url TEXT,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.timelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    name TEXT NOT NULL,
    period TEXT,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    key TEXT UNIQUE NOT NULL,
    value TEXT
);

-- 2. Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timelines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies for public read and insert/update/delete
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY['projects', 'experiences', 'certificates', 'organizations', 'timelines', 'settings'])
    LOOP
        EXECUTE format('CREATE POLICY "Enable read access for all users" ON public.%I FOR SELECT USING (true);', t);
        EXECUTE format('CREATE POLICY "Enable insert for all users" ON public.%I FOR INSERT WITH CHECK (true);', t);
        EXECUTE format('CREATE POLICY "Enable update for all users" ON public.%I FOR UPDATE USING (true);', t);
        EXECUTE format('CREATE POLICY "Enable delete for all users" ON public.%I FOR DELETE USING (true);', t);
    END LOOP;
END $$;

-- 4. Migrate data from old portfolio_items table
INSERT INTO public.projects (title, description, category, demo_url, image_url, tech_stack)
SELECT 
    title,
    SPLIT_PART(description, '|||TECH:', 1),
    position,
    link,
    image,
    CASE 
        WHEN SPLIT_PART(description, '|||TECH:', 2) != '' THEN string_to_array(SPLIT_PART(description, '|||TECH:', 2), ',')
        ELSE ARRAY[]::TEXT[]
    END
FROM public.portfolio_items
WHERE type = 'proyek';

INSERT INTO public.experiences (title, description, demo_url, image_url, sort_order)
SELECT 
    title, 
    description,
    CASE WHEN link ~ '^https?:\/\/' THEN link ELSE NULL END,
    image, 
    CASE WHEN link ~ '^[0-9]+$' THEN link::INTEGER ELSE 0 END
FROM public.portfolio_items WHERE type = 'pengalaman';

INSERT INTO public.certificates (title, issuer, category, image_url, sort_order)
SELECT 
    title, 
    description, 
    position, 
    image, 
    CASE WHEN link ~ '^[0-9]+$' THEN link::INTEGER ELSE 0 END
FROM public.portfolio_items WHERE type = 'sertifikat';

INSERT INTO public.organizations (name, role, period, icon_url, sort_order)
SELECT 
    title, 
    description, 
    position, 
    image, 
    CASE WHEN link ~ '^[0-9]+$' THEN link::INTEGER ELSE 0 END
FROM public.portfolio_items WHERE type = 'organization';

INSERT INTO public.timelines (name, period, sort_order)
SELECT 
    title, 
    position, 
    CASE WHEN link ~ '^[0-9]+$' THEN link::INTEGER ELSE 0 END
FROM public.portfolio_items WHERE type = 'timeline';

INSERT INTO public.settings (key, value)
SELECT title, link
FROM public.portfolio_items WHERE type = 'setting';

-- Note: Once you have verified the data migration, you can safely drop the old table:
-- DROP TABLE public.portfolio_items;
