-- 1. Buat Tabel untuk data Portofolio (Pengalaman & Sertifikat)
CREATE TABLE public.portfolio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    type TEXT NOT NULL, -- 'pengalaman' atau 'sertifikat'
    title TEXT NOT NULL,
    position TEXT,
    description TEXT,
    link TEXT,
    image TEXT
);

-- 2. Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan (Policy) Database
CREATE POLICY "Enable read access for all users"
ON public.portfolio_items FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users"
ON public.portfolio_items FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users"
ON public.portfolio_items FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users"
ON public.portfolio_items FOR DELETE USING (true);

-- 4. Membuat Bucket Storage 'portfolio-images'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('portfolio-images', 'portfolio-images', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Kebijakan (Policy) Storage
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT USING ( bucket_id = 'portfolio-images' );

CREATE POLICY "Allow public upload"
ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'portfolio-images' );
